//FrontHowToLearnScreen
import React from "react";
import { Button, View, Text, Image, ScrollView } from 'react-native';
import { SafeAreaView } from "react-native-safe-area-context";
import { ScreenContainerStyle, ScreenImageStyle } from "../../styles/Screen.style";
import { TextStyle } from "../../styles/Text.style";
import { ViewStyle } from "../../styles/View.style";
import { PropsNavMenu } from "../../types/propsComponent";


export default function FrontHowToLearnScreen({ navigation }: PropsNavMenu) {
    return <ScreenContainerStyle>
        <ViewStyle>
            <ScrollView>
                <Text>How to Learn How to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to Learn How to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to LearnHow to Learn</Text>
            </ScrollView>
        </ViewStyle>
    </ScreenContainerStyle>
}